// Generator for the operator-mode (T5) sender-identity fixture.
//
// Mints a throwaway operator, a system account, two service accounts and
// one user per service account, and writes:
//
//   keys.json      every seed + public key (test-only, never reuse)
//   operator.conf  `operator:` JWT, `system_account`, `resolver: MEMORY`,
//                  `resolver_preload` with the three account JWTs — port-less,
//                  like every other fixture config
//   alice.creds    ACME user (the agent side in T5)
//   carol.creds    ACME user (a same-account caller)
//   bob.creds      APP user — APP imports ACME's `agents.>` / `$SRV.>`
//                  service exports with `share: true`, so bob's requests
//                  arrive in ACME with a server-stamped `Nats-Request-Info`
//                  whose `acc` is the 56-char account public key (the NGS
//                  shape of operator-attested mode)
//
// Every JWT is issued without an expiry. Re-running the generator mints
// *new* keys (JWTs carry `iat`, so the output is never byte-identical
// anyway); commit the whole directory together. Uses `@nats-io/jwt`
// (prerelease, depends on nkeys 1.x — which is why it lives in its own
// package.json and nowhere near the SDKs).
//
//   cd test-fixtures/identity/operator && bun install && bun generate.ts

import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  Algorithms,
  createAccount,
  createOperator,
  createUser,
  encodeAccount,
  encodeOperator,
  encodeUser,
  fmtCreds,
  type KeyPair,
} from "@nats-io/jwt";

const HERE = dirname(fileURLToPath(import.meta.url));
const dec = new TextDecoder();

interface Pair {
  readonly public: string;
  readonly seed: string;
}

function pair(kp: KeyPair): Pair {
  return { public: kp.getPublicKey(), seed: dec.decode(kp.getSeed()) };
}

async function main(): Promise<void> {
  const okp = createOperator();
  const sys = createAccount();
  const acme = createAccount();
  const app = createAccount();
  const alice = createUser();
  const carol = createUser();
  const bob = createUser();

  const operatorJwt = await encodeOperator(
    "synadia-identity-test",
    okp,
    { system_account: sys.getPublicKey() },
    { algorithm: Algorithms.v2 },
  );
  // `@nats-io/jwt` writes no `limits` block; the server then reads every
  // limit as 0 ("more exports than allowed by the operator") and refuses
  // the users. Unlimited, like `nsc` defaults.
  const limits = {
    subs: -1,
    data: -1,
    payload: -1,
    imports: -1,
    exports: -1,
    wildcards: true,
    conn: -1,
    leaf: -1,
  };
  const sysJwt = await encodeAccount(
    "SYS",
    sys,
    { limits },
    { algorithm: Algorithms.v2, signer: okp },
  );
  const acmeJwt = await encodeAccount(
    "ACME",
    acme,
    {
      limits,
      exports: [
        { name: "agents", subject: "agents.>", type: "service", response_type: "Stream" },
        { name: "srv", subject: "$SRV.>", type: "service", response_type: "Stream" },
      ],
    },
    { algorithm: Algorithms.v2, signer: okp },
  );
  const appJwt = await encodeAccount(
    "APP",
    app,
    {
      limits,
      imports: [
        {
          name: "agents",
          subject: "agents.>",
          account: acme.getPublicKey(),
          type: "service",
          share: true,
        },
        {
          name: "srv",
          subject: "$SRV.>",
          account: acme.getPublicKey(),
          type: "service",
          share: true,
        },
      ],
    },
    { algorithm: Algorithms.v2, signer: okp },
  );
  const aliceJwt = await encodeUser("alice", alice, acme, {}, { algorithm: Algorithms.v2 });
  const carolJwt = await encodeUser("carol", carol, acme, {}, { algorithm: Algorithms.v2 });
  const bobJwt = await encodeUser("bob", bob, app, {}, { algorithm: Algorithms.v2 });

  const keys = {
    _comment:
      "Throwaway operator-mode keys for the T5 identity fixture. TEST-ONLY — never reuse. Regenerate with `bun generate.ts`; every file in this directory changes together.",
    operator: pair(okp),
    accounts: {
      SYS: pair(sys),
      ACME: pair(acme),
      APP: pair(app),
    },
    users: {
      alice: { ...pair(alice), account: "ACME" },
      carol: { ...pair(carol), account: "ACME" },
      bob: { ...pair(bob), account: "APP" },
    },
  };

  const conf = [
    "# Operator-mode nats-server for the T5 identity row (generated by generate.ts).",
    "# Port-less: the harnesses pass `-a 127.0.0.1 -p <port>`. Accounts are resolved",
    "# from memory; users authenticate with the .creds files next to this file.",
    "#   ACME: alice, carol — exports agents.> and $SRV.> (response_type stream)",
    "#   APP:  bob         — imports both with share: true",
    "#   SYS:  system account (no users)",
    "",
    `operator: ${operatorJwt}`,
    `system_account: ${sys.getPublicKey()}`,
    "resolver: MEMORY",
    "resolver_preload: {",
    `  ${sys.getPublicKey()}: ${sysJwt}`,
    `  ${acme.getPublicKey()}: ${acmeJwt}`,
    `  ${app.getPublicKey()}: ${appJwt}`,
    "}",
    "",
  ].join("\n");

  await writeFile(join(HERE, "keys.json"), `${JSON.stringify(keys, null, 2)}\n`);
  await writeFile(join(HERE, "operator.conf"), conf);
  await writeFile(join(HERE, "alice.creds"), fmtCreds(aliceJwt, alice));
  await writeFile(join(HERE, "carol.creds"), fmtCreds(carolJwt, carol));
  await writeFile(join(HERE, "bob.creds"), fmtCreds(bobJwt, bob));
  console.log(
    `wrote keys.json, operator.conf, alice.creds, carol.creds, bob.creds (ACME ${acme.getPublicKey()}, APP ${app.getPublicKey()})`,
  );
}

await main();
