"""Sender-identity extension — the shared codec, the caller-side options, and ``self_id``.

The extension is additive to protocol ``0.3`` and is enabled explicitly
by caller and host configuration.
The host package (``synadia_ai.agent_service``) imports the codec from
here and adds only the stateful parts (nonce cache, acceptance hook).
"""

from __future__ import annotations

from ._nkeys import base64url_decode, base64url_encode, sha256_hex, verify_with_public_key
from .agent_id import (
    ACCOUNT_LENGTH_ALLOWANCE_BYTES,
    AGENT_ID_REGEX,
    AgentId,
    assert_valid_account,
    assert_valid_user_key,
    is_account_key_shaped,
    is_user_key_shaped,
)
from .format import format_sender
from .id_sig import (
    AGENT_ID_SIGNED_INPUT_TAG,
    IDENTITY_METADATA_KEYS,
    METADATA_ACCOUNT,
    METADATA_ID_SIG,
    METADATA_USER_NKEY,
    build_agent_id_signed_input,
    sign_agent_id,
    verify_agent_id,
)
from .options import Identity
from .request_info import (
    NATS_REQUEST_INFO_HEADER,
    RequestInfoStamp,
    parse_request_info,
    read_request_info,
)
from .resolve_sender import DEFAULT_RESOLVE_TTL_S, SenderResolver, resolve_sender
from .self_id import (
    SELF_ID_NEGATIVE_TTL_S,
    SELF_ID_TIMEOUT_S,
    USER_INFO_SUBJECT,
    identity_from_user_info_reply,
    is_self_id_inflight,
    lookup_self_id,
    peek_self_id,
    refresh_self_id,
    self_id,
    self_id_failure_expired,
    start_self_id_lookup,
)
from .sender_header import (
    AGENT_SENDER_HEADER,
    AGENT_SENDER_SIGNED_INPUT_TAG,
    AGENT_SENDER_VERSION,
    DEFAULT_REPLAY_WINDOW_S,
    MAX_SENDER_HEADER_VALUE_BYTES,
    MAX_SENDER_NAME_LENGTH,
    SENDER_HEADER_FRAMING_BYTES,
    SENDER_REJECTED_DESCRIPTION,
    SIGNATURE_REQUIRED_DESCRIPTION,
    AgentSenderHeader,
    ClaimedSender,
    NonceSeen,
    SenderClaim,
    SenderInfo,
    VerifiedSender,
    VerifyMode,
    assert_valid_sender_name,
    build_claim_header,
    build_signed_input,
    check_subject_acceptance,
    encoded_header_length,
    expected_sender_header_bytes,
    format_sender_timestamp,
    max_sender_header_bytes,
    normalize_account_token_position,
    parse_sender_header,
    parse_sender_timestamp,
    read_sender_header_value,
    serialize_sender_header,
    sign_sender_header,
    verify_sender,
    verify_sender_header,
)
from .signer import (
    NkeySigner,
    ParsedCreds,
    SenderSigner,
    decode_jwt_payload,
    identity_from_jwt,
    parse_creds,
    signer_from_context,
    signer_from_creds,
    signer_from_creds_file,
    signer_from_seed,
)

__all__ = [
    "ACCOUNT_LENGTH_ALLOWANCE_BYTES",
    "AGENT_ID_REGEX",
    "AGENT_ID_SIGNED_INPUT_TAG",
    "AGENT_SENDER_HEADER",
    "AGENT_SENDER_SIGNED_INPUT_TAG",
    "AGENT_SENDER_VERSION",
    "DEFAULT_REPLAY_WINDOW_S",
    "DEFAULT_RESOLVE_TTL_S",
    "IDENTITY_METADATA_KEYS",
    "MAX_SENDER_HEADER_VALUE_BYTES",
    "MAX_SENDER_NAME_LENGTH",
    "METADATA_ACCOUNT",
    "METADATA_ID_SIG",
    "METADATA_USER_NKEY",
    "NATS_REQUEST_INFO_HEADER",
    "SELF_ID_NEGATIVE_TTL_S",
    "SELF_ID_TIMEOUT_S",
    "SENDER_HEADER_FRAMING_BYTES",
    "SENDER_REJECTED_DESCRIPTION",
    "SIGNATURE_REQUIRED_DESCRIPTION",
    "USER_INFO_SUBJECT",
    "AgentId",
    "AgentSenderHeader",
    "ClaimedSender",
    "Identity",
    "NkeySigner",
    "NonceSeen",
    "ParsedCreds",
    "RequestInfoStamp",
    "SenderClaim",
    "SenderInfo",
    "SenderResolver",
    "SenderSigner",
    "VerifiedSender",
    "VerifyMode",
    "assert_valid_account",
    "assert_valid_sender_name",
    "assert_valid_user_key",
    "base64url_decode",
    "base64url_encode",
    "build_agent_id_signed_input",
    "build_claim_header",
    "build_signed_input",
    "check_subject_acceptance",
    "decode_jwt_payload",
    "encoded_header_length",
    "expected_sender_header_bytes",
    "format_sender",
    "format_sender_timestamp",
    "identity_from_jwt",
    "identity_from_user_info_reply",
    "is_account_key_shaped",
    "is_self_id_inflight",
    "is_user_key_shaped",
    "lookup_self_id",
    "max_sender_header_bytes",
    "normalize_account_token_position",
    "parse_creds",
    "parse_request_info",
    "parse_sender_header",
    "parse_sender_timestamp",
    "peek_self_id",
    "read_request_info",
    "read_sender_header_value",
    "refresh_self_id",
    "resolve_sender",
    "self_id",
    "self_id_failure_expired",
    "serialize_sender_header",
    "sha256_hex",
    "sign_agent_id",
    "sign_sender_header",
    "signer_from_context",
    "signer_from_creds",
    "signer_from_creds_file",
    "signer_from_seed",
    "start_self_id_lookup",
    "verify_agent_id",
    "verify_sender",
    "verify_sender_header",
    "verify_with_public_key",
]
