"""``Agent-Sender`` codec (unit, no server).

Known-answer vectors (``test-fixtures/identity/sender-vectors.json``,
generated by the TypeScript SDK): the Python implementation reproduces
every header byte, signed input and signature, and the framed wire
length. Then the parser-hardening rows of plan §2.2, the size bound vs
the exact size, subject acceptance (equality / token removal), and the
verification outcomes.
"""

from __future__ import annotations

import base64
import calendar
import json
import time
from typing import TYPE_CHECKING, Any

import pytest

from synadia_ai.agents import (
    AgentId,
    AgentSenderHeader,
    ClaimedSender,
    IdentityError,
    MalformedSenderHeaderError,
    SenderVerificationError,
    VerifiedSender,
    build_claim_header,
    check_subject_acceptance,
    encoded_header_length,
    expected_sender_header_bytes,
    format_sender,
    format_sender_timestamp,
    max_sender_header_bytes,
    normalize_account_token_position,
    parse_sender_header,
    read_sender_header_value,
    serialize_sender_header,
    sign_sender_header,
    verify_sender,
    verify_sender_header,
)
from synadia_ai.agents.identity import (
    SENDER_HEADER_FRAMING_BYTES,
    assert_valid_sender_name,
    base64url_encode,
    build_signed_input,
    parse_sender_timestamp,
    sha256_hex,
    signer_from_seed,
    verify_with_public_key,
)
from tests.harness.nats_server import identity_fixture

if TYPE_CHECKING:
    from synadia_ai.agents.identity import NkeySigner
    from tests.conftest import NkeyUser

VECTORS: dict[str, Any] = json.loads(
    identity_fixture("sender-vectors.json").read_text(encoding="utf-8")
)
SUBJECT = "agents.prompt.demo.alice.example"
PAYLOAD = b'{"prompt":"hello"}'
SIGNATURE_LENGTH = 86
NUID_LENGTH = 22
MIN_VECTORS = 8
NAME_CAP = 64
C1_NEL = "\x85"
LINE_SEP = "\u2028"


@pytest.fixture(scope="module")
def alice(identity_keys: dict[str, NkeyUser]) -> NkeySigner:
    return signer_from_seed(identity_keys["alice"].seed)


@pytest.fixture(scope="module")
def bob(identity_keys: dict[str, NkeyUser]) -> NkeySigner:
    return signer_from_seed(identity_keys["bob"].seed)


@pytest.fixture(scope="module")
def alice_id(alice: NkeySigner) -> AgentId:
    return AgentId.new("$G", alice.public_key)


async def _signed(alice: NkeySigner, alice_id: AgentId, **overrides: Any) -> AgentSenderHeader:
    kwargs: dict[str, Any] = {"signer": alice, "id": alice_id, "sub": SUBJECT, "payload": PAYLOAD}
    kwargs.update(overrides)
    return await sign_sender_header(**kwargs)


def _with(h: AgentSenderHeader, **patch: Any) -> str:
    o = json.loads(serialize_sender_header(h))
    for k, v in patch.items():
        if v is None:
            o.pop(k, None)
        else:
            o[k] = v
    return json.dumps(o, separators=(",", ":"), ensure_ascii=False)


# --- vectors ---------------------------------------------------------------


def test_vector_file_shape() -> None:
    assert VECTORS["header_framing_bytes"] == SENDER_HEADER_FRAMING_BYTES
    vectors = VECTORS["vectors"]
    assert len(vectors) >= MIN_VECTORS
    assert any(v["input"]["payload_b64"] == "" for v in vectors)
    assert any(not v["input"]["signed"] for v in vectors)
    assert any(not v["input"].get("name", "").isascii() for v in vectors)
    assert any("sub" in v["input"] for v in vectors)


@pytest.mark.parametrize("v", VECTORS["vectors"], ids=[v["id"] for v in VECTORS["vectors"]])
async def test_vector(v: dict[str, Any]) -> None:
    inp, exp = v["input"], v["expected"]
    signer = signer_from_seed(inp["seed"])
    assert signer.public_key == inp["user"]
    id = AgentId.new(inp["account"], inp["user"])
    payload = base64.b64decode(inp["payload_b64"])
    sub = inp.get("sub", inp["subject"])
    name = inp.get("name")

    if inp["signed"]:
        header = await sign_sender_header(
            signer=signer,
            id=id,
            sub=sub,
            payload=payload,
            name=name,
            ts=inp["ts"],
            nonce=inp["nonce"],
        )
    else:
        header = build_claim_header(id=id, name=name)

    value = serialize_sender_header(header)
    assert value == exp["header"]
    assert len(value.encode("utf-8")) == exp["header_bytes"]
    assert encoded_header_length(value) == exp["header_wire_bytes"]
    assert exp["header_wire_bytes"] == exp["header_bytes"] + SENDER_HEADER_FRAMING_BYTES
    assert encoded_header_length(value) <= max_sender_header_bytes(sub, name)

    parsed = parse_sender_header(exp["header"])
    assert parsed == header

    if inp["signed"]:
        data = build_signed_input(
            account=inp["account"],
            user=inp["user"],
            subject=sub,
            ts=inp["ts"],
            nonce=inp["nonce"],
            payload_sha256_hex=sha256_hex(payload),
        )
        assert data.decode("utf-8") == exp["signed_input"]
        assert header.sig == exp["sig"]
        assert verify_with_public_key(
            inp["user"], data, base64.urlsafe_b64decode(exp["sig"] + "==")
        )
        assert parsed is not None
        # Stored-mode verification against the signed subject (ts is fixed in the past).
        verified = verify_sender_header(parsed, sub, payload, mode="stored")
        assert isinstance(verified, VerifiedSender)
        assert verified.id == id
        assert verified.name == name
        assert verified.account_attested is False
        # Exact size accounting matches the vector for a NUID-length nonce.
        if len(inp["nonce"]) == NUID_LENGTH:
            assert (
                expected_sender_header_bytes(id=id, sub=sub, signed=True, name=name)
                == (exp["header_wire_bytes"])
            )
    else:
        assert "signed_input" not in exp
        assert parsed is not None
        claimed = verify_sender_header(parsed, sub, payload, mode="live")
        assert isinstance(claimed, ClaimedSender)
        assert not hasattr(claimed, "id")
        assert (
            expected_sender_header_bytes(id=id, sub=sub, signed=False, name=name)
            == (exp["header_wire_bytes"])
        )


# --- serialisation ---------------------------------------------------------


def test_serialize_fixed_order_compact_v_integer(alice: NkeySigner, alice_id: AgentId) -> None:
    assert (
        serialize_sender_header(build_claim_header(id=alice_id))
        == f'{{"v":1,"account":"$G","user":"{alice.public_key}"}}'
    )
    assert (
        serialize_sender_header(build_claim_header(id=alice_id, name="x"))
        == f'{{"v":1,"account":"$G","user":"{alice.public_key}","name":"x"}}'
    )


def test_serialize_keeps_non_ascii_raw(alice_id: AgentId) -> None:
    s = serialize_sender_header(build_claim_header(id=alice_id, name="Bob · 日本語 🤖"))
    assert '"name":"Bob · 日本語 🤖"' in s
    assert "\\u" not in s


async def test_serialize_orders_sub_ts_nonce_sig_after_name(
    alice: NkeySigner, alice_id: AgentId
) -> None:
    h = await _signed(alice, alice_id, name="n", ts="2026-08-28T12:00:00Z", nonce="abc")
    assert list(json.loads(serialize_sender_header(h))) == [
        "v",
        "account",
        "user",
        "name",
        "sub",
        "ts",
        "nonce",
        "sig",
    ]


# --- signing ---------------------------------------------------------------


async def test_sign_emits_second_precision_ts_nuid_nonce_and_86_char_sig(
    alice: NkeySigner, alice_id: AgentId
) -> None:
    h = await _signed(alice, alice_id)
    assert h.ts is not None and h.nonce is not None and h.sig is not None
    assert len(h.ts) == len("2026-08-28T12:00:00Z") and h.ts.endswith("Z")
    assert len(h.nonce) == NUID_LENGTH
    assert len(h.sig) == SIGNATURE_LENGTH
    assert h.sub == SUBJECT
    other = await _signed(alice, alice_id)
    assert other.nonce != h.nonce  # fresh nonce per call


def test_format_sender_timestamp_drops_fractions() -> None:
    noon = calendar.timegm((2026, 8, 28, 12, 0, 0))
    assert format_sender_timestamp(noon + 0.999) == "2026-08-28T12:00:00Z"
    assert parse_sender_timestamp("2026-08-28T12:00:00Z") == noon
    assert parse_sender_timestamp("2026-08-28T12:00:00.5Z") == noon + 0.5


async def test_async_signer_is_awaited(alice: NkeySigner, alice_id: AgentId) -> None:
    class AsyncSigner:
        public_key = alice.public_key
        jwt = None

        async def sign(self, data: bytes) -> bytes:
            return alice.sign(data)

    h = await sign_sender_header(signer=AsyncSigner(), id=alice_id, sub=SUBJECT, payload=PAYLOAD)
    assert isinstance(verify_sender_header(h, SUBJECT, PAYLOAD, mode="live"), VerifiedSender)


# --- name validation -------------------------------------------------------


def test_name_rules_count_utf16_units_and_reject_controls() -> None:
    assert_valid_sender_name("x" * NAME_CAP)
    assert_valid_sender_name("Bob · 日本語")
    with pytest.raises(IdentityError, match="64 UTF-16 code units"):
        assert_valid_sender_name("x" * (NAME_CAP + 1))
    with pytest.raises(IdentityError, match="64 UTF-16 code units"):
        assert_valid_sender_name("🤖" * (NAME_CAP // 2 + 1))  # an emoji counts 2
    assert_valid_sender_name("🤖" * (NAME_CAP // 2))
    for bad in ("a\nb", "a\tb", f"a{C1_NEL}b", "a\x7fb", f"a{LINE_SEP}b"):
        with pytest.raises(IdentityError, match="control character"):
            assert_valid_sender_name(bad)
    with pytest.raises(IdentityError, match="lone surrogate"):
        assert_valid_sender_name("a\ud800b")
    # The message never echoes the name.
    try:
        assert_valid_sender_name("secret\n")
    except IdentityError as exc:
        assert "secret" not in str(exc)


# --- parser hardening ------------------------------------------------------


async def test_parse_round_trips_and_ignores_unknown_fields(
    alice: NkeySigner, alice_id: AgentId
) -> None:
    h = await _signed(alice, alice_id, name="claude-code")
    parsed = parse_sender_header(_with(h, extra={"deep": True}, zzz=1))
    assert parsed == h


async def test_unknown_numeric_v_is_absent(alice: NkeySigner, alice_id: AgentId) -> None:
    h = await _signed(alice, alice_id)
    assert parse_sender_header(_with(h, v=2)) is None
    assert parse_sender_header(_with(h, v=1.0)) == h  # JSON 1.0 is the number 1


@pytest.mark.parametrize(
    ("label", "patch"),
    [
        ("v as string", {"v": "1"}),
        ("v as boolean", {"v": True}),
        ("v missing", {"v": None}),
    ],
)
async def test_rejects_bad_v(
    alice: NkeySigner, alice_id: AgentId, label: str, patch: dict[str, Any]
) -> None:
    h = await _signed(alice, alice_id)
    with pytest.raises(MalformedSenderHeaderError, match="`v`"):
        parse_sender_header(_with(h, **patch))


def test_rejects_non_json_non_object_and_oversize(alice: NkeySigner) -> None:
    with pytest.raises(MalformedSenderHeaderError, match="not valid JSON"):
        parse_sender_header("not json")
    with pytest.raises(MalformedSenderHeaderError, match="not a JSON object"):
        parse_sender_header("[1]")
    big = f'{{"v":1,"account":"$G","user":"{alice.public_key}","pad":"{"x" * 2100}"}}'
    with pytest.raises(MalformedSenderHeaderError, match="exceeds 2048"):
        parse_sender_header(big)


async def test_rejects_bad_user_account_or_missing(alice: NkeySigner, alice_id: AgentId) -> None:
    h = await _signed(alice, alice_id)
    with pytest.raises(MalformedSenderHeaderError):
        parse_sender_header(_with(h, user=h.user[:55]))
    with pytest.raises(MalformedSenderHeaderError, match="nkeys check"):
        parse_sender_header(
            _with(h, account="AABYLMBR6Q2CDXTLGRQCFA2GP76BGCDF7NZF2OVHH4RQ7L3Y3TZWJDRM")
        )
    with pytest.raises(MalformedSenderHeaderError, match="must be strings"):
        parse_sender_header(f'{{"v":1,"user":"{alice.public_key}"}}')
    with pytest.raises(MalformedSenderHeaderError, match="must be strings"):
        parse_sender_header('{"v":1,"account":"$G"}')


@pytest.mark.parametrize("missing", ["sub", "ts", "nonce"])
async def test_sig_requires_sub_ts_nonce(
    alice: NkeySigner, alice_id: AgentId, missing: str
) -> None:
    h = await _signed(alice, alice_id)
    with pytest.raises(MalformedSenderHeaderError, match="requires"):
        parse_sender_header(_with(h, **{missing: None}))


@pytest.mark.parametrize(
    "ts",
    [
        "yesterday",
        "2026-08-28 12:00:00Z",
        "2026-08-28T12:00:00",
        "2026-08-28T12:00:00+00:00",
        "2026-13-28T12:00:00Z",
        "2026-08-28T12:00:00.Z",
    ],
)
async def test_rejects_bad_ts(alice: NkeySigner, alice_id: AgentId, ts: str) -> None:
    h = await _signed(alice, alice_id)
    with pytest.raises(MalformedSenderHeaderError, match="`ts`"):
        parse_sender_header(_with(h, ts=ts))


async def test_accepts_fractional_seconds(alice: NkeySigner, alice_id: AgentId) -> None:
    h = await _signed(alice, alice_id)
    parsed = parse_sender_header(_with(h, ts="2026-08-28T12:00:00.123Z"))
    assert parsed is not None and parsed.ts == "2026-08-28T12:00:00.123Z"


@pytest.mark.parametrize("nonce", ["", "a.b", "has space", "x" * 65, "ünïcode"])
async def test_rejects_bad_nonce(alice: NkeySigner, alice_id: AgentId, nonce: str) -> None:
    h = await _signed(alice, alice_id)
    with pytest.raises(MalformedSenderHeaderError, match="`nonce`"):
        parse_sender_header(_with(h, nonce=nonce))


async def test_rejects_bad_sig(alice: NkeySigner, alice_id: AgentId) -> None:
    h = await _signed(alice, alice_id)
    with pytest.raises(MalformedSenderHeaderError, match="base64url"):
        parse_sender_header(_with(h, sig="not base64url!"))
    with pytest.raises(MalformedSenderHeaderError, match="64 bytes"):
        parse_sender_header(_with(h, sig=base64url_encode(bytes(63))))
    with pytest.raises(MalformedSenderHeaderError, match="base64url"):
        parse_sender_header(_with(h, sig=(h.sig or "") + "="))
    with pytest.raises(MalformedSenderHeaderError, match="`sig` must be a string"):
        parse_sender_header(_with(h, sig=5))


async def test_rejects_bad_name(alice: NkeySigner, alice_id: AgentId) -> None:
    h = await _signed(alice, alice_id)
    for name in ("a\nb", "x" * (NAME_CAP + 1), 5, f"a{C1_NEL}b", None):
        value = (
            _with(h, name=name)
            if name is not None
            else _with(h).replace('"user":', '"name":null,"user":', 1)
        )
        with pytest.raises(MalformedSenderHeaderError, match="display name"):
            parse_sender_header(value)


@pytest.mark.parametrize("sub", ["", "a..b", "a b", ".a", "a.", "a\tb"])
async def test_rejects_bad_sub(alice: NkeySigner, alice_id: AgentId, sub: str) -> None:
    h = await _signed(alice, alice_id)
    with pytest.raises(MalformedSenderHeaderError, match="`sub`"):
        parse_sender_header(_with(h, sub=sub))


def test_read_sender_header_value_cases() -> None:
    assert read_sender_header_value(None) is None
    assert read_sender_header_value({}) is None
    assert read_sender_header_value({"agent-sender": "{}"}) is None  # exact case only
    assert read_sender_header_value({"Agent-Sender": "{}"}) == "{}"
    assert read_sender_header_value({"Agent-Sender": ["{}"]}) == "{}"
    assert read_sender_header_value({"Agent-Sender": []}) is None
    with pytest.raises(MalformedSenderHeaderError, match="more than one"):
        read_sender_header_value({"Agent-Sender": ["{}", "{}"]})
    with pytest.raises(MalformedSenderHeaderError, match="not a string"):
        read_sender_header_value({"Agent-Sender": 5})


# --- size bound ------------------------------------------------------------


async def test_bound_dominates_exact_size_for_every_shape(
    alice: NkeySigner, alice_id: AgentId
) -> None:
    for name in (None, "x", "n" * NAME_CAP, "Bob · 日本語 🤖"):
        for sub in ("a", SUBJECT, "svc.APP.prompt." + "t" * 40):
            h = await _signed(alice, alice_id, sub=sub, name=name)
            exact = encoded_header_length(serialize_sender_header(h))
            assert exact == expected_sender_header_bytes(
                id=alice_id, sub=sub, signed=True, name=name
            )
            assert exact <= max_sender_header_bytes(sub, name)
            claim = encoded_header_length(
                serialize_sender_header(build_claim_header(id=alice_id, name=name))
            )
            assert claim == expected_sender_header_bytes(
                id=alice_id, sub=sub, signed=False, name=name
            )
            assert claim <= max_sender_header_bytes(sub, name)


# --- subject acceptance ----------------------------------------------------


def test_subject_acceptance_equality_and_token_removal() -> None:
    ok = check_subject_acceptance
    assert ok(account="APP", sub="a.b", arrival_subject="a.b", account_token_position=None) is None
    assert ok(account="APP", sub="a.b", arrival_subject="a.c", account_token_position=None)
    # Token inserted at position 2: `svc.prompt` published, `svc.APP.prompt` arrives.
    assert (
        ok(
            account="APP",
            sub="svc.prompt",
            arrival_subject="svc.APP.prompt",
            account_token_position=2,
        )
        is None
    )
    assert (
        ok(
            account="APP",
            sub="svc.APP.prompt",
            arrival_subject="svc.APP.prompt",
            account_token_position=2,
        )
        is None
    )
    assert "not the header account" in (
        ok(
            account="EVIL",
            sub="svc.prompt",
            arrival_subject="svc.APP.prompt",
            account_token_position=2,
        )
        or ""
    )
    assert "beyond" in (
        ok(
            account="APP",
            sub="svc.prompt",
            arrival_subject="svc.APP.prompt",
            account_token_position=5,
        )
        or ""
    )
    assert "neither" in (
        ok(
            account="APP",
            sub="other.prompt",
            arrival_subject="svc.APP.prompt",
            account_token_position=2,
        )
        or ""
    )
    assert normalize_account_token_position(None) is None
    assert normalize_account_token_position(1) == 1
    for bad in (0, -1, 1.5, True, "2"):
        with pytest.raises(IdentityError, match="1-based"):
            normalize_account_token_position(bad)  # type: ignore[arg-type]


# --- verification outcomes -------------------------------------------------


async def test_verify_live_outcomes(alice: NkeySigner, bob: NkeySigner, alice_id: AgentId) -> None:
    h = await _signed(alice, alice_id, name="n")
    ok = verify_sender_header(h, SUBJECT, PAYLOAD, mode="live")
    assert isinstance(ok, VerifiedSender)
    assert ok.id == alice_id and ok.name == "n" and ok.header is h
    assert await ok.resolve() is None  # unbound resolver
    assert str(ok) == f"{alice_id} (verified user, claimed account)"

    def rejected(
        header: AgentSenderHeader, arrival: str = SUBJECT, payload: bytes = PAYLOAD, **o: Any
    ) -> str:
        with pytest.raises(SenderVerificationError) as exc_info:
            verify_sender_header(header, arrival, payload, mode="live", **o)
        assert exc_info.value.code == 401
        assert exc_info.value.description == "sender rejected"
        return exc_info.value.detail

    assert "arrival subject" in rejected(h, "agents.prompt.demo.alice.other")
    assert "does not verify" in rejected(h, SUBJECT, b'{"prompt":"ho"}')
    stale = await _signed(alice, alice_id, ts=format_sender_timestamp(time.time() - 120))
    assert "window" in rejected(stale)
    future = await _signed(alice, alice_id, ts=format_sender_timestamp(time.time() + 29))
    assert isinstance(verify_sender_header(future, SUBJECT, PAYLOAD, mode="live"), VerifiedSender)
    replay_detail = rejected(h, nonce_seen=lambda _u, _n: True)
    assert "already seen" in replay_detail
    assert h.nonce is not None and h.nonce not in replay_detail
    # Rewritten fields: the parsed header still verifies the *signature* against its own fields,
    # so a rewritten `account`/`user` fails the ed25519 check.
    parsed = parse_sender_header(_with(h, account="ACME"))
    assert parsed is not None and "does not verify" in rejected(parsed)
    parsed = parse_sender_header(_with(h, user=bob.public_key))
    assert parsed is not None and "does not verify" in rejected(parsed)
    # `name` is outside the signature: a mutated name still verifies.
    parsed = parse_sender_header(_with(h, name="relay-rewrote-me"))
    assert parsed is not None
    assert isinstance(verify_sender_header(parsed, SUBJECT, PAYLOAD, mode="live"), VerifiedSender)
    # Stored mode: no freshness, no nonce lookup.
    assert isinstance(
        verify_sender_header(
            stale, SUBJECT, PAYLOAD, mode="stored", nonce_seen=lambda _u, _n: True
        ),
        VerifiedSender,
    )
    # A custom replay window and clock.
    assert "window" in rejected(h, replay_window_s=1.0, now=time.time() + 5)


async def test_verify_binds_resolver(alice: NkeySigner, alice_id: AgentId) -> None:
    h = await _signed(alice, alice_id)
    asked: list[AgentId] = []

    async def resolver(id: AgentId) -> None:
        asked.append(id)

    sender = verify_sender_header(h, SUBJECT, PAYLOAD, mode="live", resolver=resolver)
    assert isinstance(sender, VerifiedSender)
    assert await sender.resolve() is None
    assert asked == [alice_id]


async def test_verify_sender_over_a_structural_message(
    alice: NkeySigner, alice_id: AgentId
) -> None:
    class FakeMsg:
        def __init__(self, headers: dict[str, str] | None) -> None:
            self.subject = SUBJECT
            self.data = PAYLOAD
            self.headers = headers

    h = await _signed(alice, alice_id)
    assert verify_sender(FakeMsg(None), "live") is None
    assert verify_sender(FakeMsg({"agent-sender": serialize_sender_header(h)}), "live") is None
    assert verify_sender(FakeMsg({"Agent-Sender": _with(h, v=2)}), "live") is None
    got = verify_sender(FakeMsg({"Agent-Sender": serialize_sender_header(h)}), "live")
    assert isinstance(got, VerifiedSender)
    with pytest.raises(MalformedSenderHeaderError):
        verify_sender(FakeMsg({"Agent-Sender": "{"}), "live")


def test_format_sender_forms(alice_id: AgentId) -> None:
    header = AgentSenderHeader(account=alice_id.account, user=alice_id.user)
    verified = VerifiedSender(id=alice_id, header=header)
    assert format_sender(verified) == f"{alice_id} (verified user, claimed account)"
    attested = VerifiedSender(id=alice_id, header=header, account_attested=True)
    assert format_sender(attested) == f"{alice_id} (verified)"
    claimed = ClaimedSender(
        claim=__import__("synadia_ai.agents", fromlist=["SenderClaim"]).SenderClaim(
            account=alice_id.account, user=alice_id.user
        ),
        header=header,
    )
    assert format_sender(claimed) == f"{alice_id} (claimed)"
    assert str(claimed) == f"{alice_id} (claimed)"
    assert format_sender(None) == "(no sender)"
    assert verified.trust == "verified" and claimed.trust == "claimed"


# --- operator-attested cross-check (spec Appendix A; PR-T2 rules, byte for byte) -----


async def test_verify_operator_attested_cross_check(
    alice: NkeySigner, bob: NkeySigner, alice_id: AgentId
) -> None:
    h = await _signed(alice, alice_id)
    stamp_ok = {"Nats-Request-Info": json.dumps({"acc": alice_id.account, "user": alice_id.user})}
    stamp_acc = {"Nats-Request-Info": json.dumps({"acc": alice_id.account, "rtt": 1})}

    def verify(headers: dict[str, str] | None, **o: Any) -> VerifiedSender:
        got = verify_sender_header(
            h, SUBJECT, PAYLOAD, mode="live", operator_attested=True, headers=headers, **o
        )
        assert isinstance(got, VerifiedSender)
        return got

    def rejected(headers: dict[str, str] | None, **o: Any) -> str:
        with pytest.raises(SenderVerificationError) as exc_info:
            verify_sender_header(
                h, SUBJECT, PAYLOAD, mode="live", operator_attested=True, headers=headers, **o
            )
        assert exc_info.value.code == 401
        assert exc_info.value.description == "sender rejected"
        return exc_info.value.detail

    # Off by default: the stamp is never read, `account_attested` stays False.
    off = verify_sender_header(
        h, SUBJECT, PAYLOAD, mode="live", headers={"Nats-Request-Info": '{"acc":"EVIL"}'}
    )
    assert isinstance(off, VerifiedSender) and off.account_attested is False
    # Agreement on `acc` (+ `user`) attests the account; `format_sender` → `(verified)`.
    assert verify(stamp_ok).account_attested is True
    assert str(verify(stamp_ok)) == f"{alice_id} (verified)"
    # A no-`share` stamp (`acc` only) attests too: `user` is verified by the signature.
    assert verify(stamp_acc).account_attested is True
    # An absent stamp is compared to nothing — verified, not attested.
    assert verify(None).account_attested is False
    assert verify({}).account_attested is False
    # Disagreement on either field → 401 with the field in the detail.
    assert "acc 'APP' disagrees" in rejected({"Nats-Request-Info": '{"acc":"APP"}'})
    assert f"user {bob.public_key!r} disagrees" in rejected(
        {"Nats-Request-Info": json.dumps({"acc": alice_id.account, "user": bob.public_key})}
    )
    # A stamp the server would not write → 401.
    assert "not a server stamp" in rejected({"Nats-Request-Info": "{"})
    assert "not a server stamp" in rejected({"Nats-Request-Info": '{"acc":7}'})
    # The `account_token_position` cross-check counts as attestation on its own.
    arrival = "svc." + alice_id.account + ".prompt"
    h_svc = await _signed(alice, alice_id, sub="svc.prompt")
    got = verify_sender_header(
        h_svc, arrival, PAYLOAD, mode="live", operator_attested=True, account_token_position=2
    )
    assert isinstance(got, VerifiedSender) and got.account_attested is True
    # Claims are never cross-checked.
    claim = parse_sender_header(serialize_sender_header(build_claim_header(id=alice_id)))
    assert claim is not None
    got_claim = verify_sender_header(
        claim,
        SUBJECT,
        PAYLOAD,
        mode="live",
        operator_attested=True,
        headers={"Nats-Request-Info": '{"acc":"EVIL"}'},
    )
    assert isinstance(got_claim, ClaimedSender)
    # `verify_sender(msg, mode, operator_attested=True)` reads the stamp from `msg.headers`.

    class FakeMsg:
        def __init__(self, headers: dict[str, str]) -> None:
            self.subject = SUBJECT
            self.data = PAYLOAD
            self.headers = headers

    both = {"Agent-Sender": serialize_sender_header(h), **stamp_ok}
    got_msg = verify_sender(FakeMsg(both), "live", operator_attested=True)
    assert isinstance(got_msg, VerifiedSender) and got_msg.account_attested is True
    with pytest.raises(SenderVerificationError):
        verify_sender(
            FakeMsg({"Agent-Sender": serialize_sender_header(h), "Nats-Request-Info": "{"}),
            "live",
            operator_attested=True,
        )
